# Generated by Django 4.2.7 on 2024-11-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_card_id_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='card_id',
        ),
    ]
