# Generated by Django 4.2.7 on 2024-11-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartorderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='applied_cupon',
            new_name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
    ]
