# Generated by Django 4.2.7 on 2024-11-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantitem',
            old_name='prview',
            new_name='preview',
        ),
    ]
