# Generated by Django 4.2.7 on 2024-11-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_prview_variantitem_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantitem',
            old_name='preview',
            new_name='prview',
        ),
    ]
