# Generated by Django 4.2.7 on 2024-11-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_preview_variantitem_prview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantitem',
            old_name='prview',
            new_name='preview',
        ),
    ]
