# Generated by Django 4.2.7 on 2024-11-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_linkedin_teacher_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='sub_totoal',
            new_name='sub_total',
        ),
    ]
