# Generated by Django 4.2.7 on 2024-11-21 02:12

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_sub_totoal_cartorder_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='repy',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='question_answer_message',
            name='qa_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Ukrainian', 'Ukrainian'), ('English', 'English')], default='English', max_length=100),
        ),
    ]
