# Generated by Django 4.2.7 on 2024-11-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_repy_review_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Ukrainian', 'Ukrainian'), ('English', 'English')], default='Ukrainian', max_length=100),
        ),
    ]
