# Generated by Django 4.2.7 on 2024-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_course_is_free_alter_course_file_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Українська', 'Українська'), ('English', 'English')], default='Українська', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Початківець', 'Початківець'), ('Середній', 'Середній'), ('Продвинутий', 'Продвинутий')], default='Початківець', max_length=100),
        ),
    ]
